### ISSUE TITLE
Screenshot on #40 is missing

### ISSUE THREAD

**Issue by FREDVUNI** [AsmrProg-YT/100-days-of-javascript#12]
The image is broken on #40

![image](https://github.com/AsmrProg-YT/100-days-of-javascript/assets/41730664/38bc14df-9bee-41b7-b21a-d46904822260)

**Comment by FREDVUNI** [comment]
@AsmrProg-YT, I have raised a [PR](https://github.com/AsmrProg-YT/100-days-of-javascript/pull/16) for this, It fixes the issue

**Comment by FREDVUNI** [comment]
screenshot:
![image](https://github.com/AsmrProg-YT/100-days-of-javascript/assets/41730664/51950841-a52e-4fe4-8472-dcd2e1301dba)

**Comment by AsmrProg-YT** [comment]
Hi, I have added it, thanks for letting me know.
