### ISSUE TITLE
Always error on on the chatgpt

### ISSUE THREAD

**Issue by Bibou1494** [AsmrProg-YT/100-days-of-javascript#19]
Hello. I dont know why but i have only error when i try asking gpt with rapidapi. Here is the proof that i have error.
![Screenshot_20240105_201455_Chrome.jpg](https://github.com/AsmrProg-YT/100-days-of-javascript/assets/132447113/08b097a7-29e0-4abb-922d-f2b703d08584)

That anoying because i want to use gpt without buying anything.

**Comment by Tim-Benjamin** [comment]
i also have the same issue

**Comment by Bibou1494** [comment]
i gonna close because now chat gpt is free, with a subscription

**Comment by w3teal** [comment]
Are you already change the API key to your own?
https://github.com/AsmrProg-YT/100-days-of-javascript/blob/318e98eafb054c233a9f2f5b6a9ed07b1184daab/Day%20%2331%20-%20ChatGPT%20Bot/index.js#L46
It's also showed in the tutorial video: https://youtu.be/xsNKwwhKfRI?t=895

**Comment by Bibou1494** [comment]
Yeah i've did change it
